### ISSUE TITLE
Autosaving file

### ISSUE THREAD

**Issue by lbertelo01** [RADar-AZDelta/Keun#194]
Would it be possible to automatically and frequently save the file that is currently worked on in Keun?

Accidently closing the keun page, forgetting to save the file before downloading, etc. would then not cause loss of work that had been done.

Thanks!

**Comment by BostoenToby** [comment]
I've added this feature in the past, but when testing the application it proved unreliable.
For this reason, I've added the save button.

The file would be saved on the event called "beforeNavigate", but the problem with this is that it sometimes navigates before completing the save.

I'll check what I can do to improve this so that it's reliable.

**Comment by BostoenToby** [comment]
Normally, this feature is enabled again.
I've kept the save button for people who like to manually save the file, but normally when leaving the page by one of the following ways will trigger the auto save:

- Navigate through the back/forward arrows of the browser
- Close the tab
- Navigate to file selection
- Navigate through the address bar in the browser
